# This workflow will do a clean install of node dependencies, build the source code, run tests and deploy to pages

name: Deploy to GitHub Pages

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.build.outputs.version }}
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 19.x
    - name: Yarn install
      run: yarn
    - name: Build
      id: build
      run: |
        yarn build
        cp .htaccess dist
        cp CNAME dist
        echo "version=$(yarn ver)" >> $GITHUB_OUTPUT
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: dist
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: yarn test
      continue-on-error: true
  deploy:
    runs-on: ubuntu-latest
    needs: [ build, test ]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - echo: echo deploying version ${{ needs.build.outputs.version }}
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
