# This workflow will do a clean install of node dependencies, build the source code and run tests

name: Build feature

on:
  push:
    branches: [ feature/** ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 19.x
    - name: Yarn install
      run: yarn
    - name: Build
      run: yarn build
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: yarn test
      continue-on-error: true
